// LOCALHOST
GET http://localhost:3000/

###
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/69fcaa611e19d92fdcf101a0


// PRODUCTION Deploy
###
GET https://cse341spring26.onrender.com

###
GET https://cse341spring26.onrender.com/contacts

###
GET https://cse341spring26.onrender.com/contacts/69fcaa611e19d92fdcf101a0


###
// LOCALHOST - create a contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
	"firstName": "John",
	"lastName": "Doe",
	"email": "test.user@example.com",
	"favoriteColor": "blue",
	"birthday": "1990-01-01"
}

###
// LOCALHOST - update a contact
PUT http://localhost:3000/contacts/6a001fbf2216fdea6a684ada
Content-Type: application/json

{
	"firstName": "Updated",
	"lastName": "User",
	"email": "updated.user@example.com",
	"favoriteColor": "green",
	"birthday": "2000-02-02"
}

###
// LOCALHOST - delete a contact
DELETE http://localhost:3000/contacts/6a001fbf2216fdea6a684ada
###
// PRODUCTION - create a contact
POST https://cse341spring26.onrender.com/contacts
Content-Type: application/json

{
	"firstName": "Ted",
	"lastName": "User",
	"email": "test.user@example.com",
	"favoriteColor": "blue",
	"birthday": "1990-01-01"
}

###
// PRODUCTION - update a contact
PUT https://cse341spring26.onrender.com/contacts/6a001ff1f060c81e8c127697
Content-Type: application/json

{
	"firstName": "Bill",
	"lastName": "User",
	"email": "updated.user@example.com",
	"favoriteColor": "green",
	"birthday": "1990-02-02"
}

###
// PRODUCTION - delete a contact
DELETE https://cse341spring26.onrender.com/contacts/6a001ff1f060c81e8c127697
